version: '3.8'

services:
  web:
    build: .
    container_name: flask-app-container
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://eden:1234@postgres:5432/postgres_db
    volumes:
      - .:/app
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres-db-container
    environment:
      POSTGRES_USER: eden
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
